# Errors

An error in find_faces

Mon 26 Feb 2024 18:10

hojelse@hojelse thesis % python3 count_hamcyc_faster.py < graphs/20-12809.bin
Traceback (most recent call last):
  File "/Users/hojelse/repo/thesis/count_hamcyc_faster.py", line 47, in <module>
    faces = find_faces(adj)
  File "/Users/hojelse/repo/thesis/count_hamcyc_faster.py", line 31, in find_faces
    edges.remove(next_edge)
KeyError: (5, 4)

